openapi: 3.0.3
info:
  title: Quote Management API
  version: 1.0.0
  description: API for managing quotes in a system
paths:
  /api/quotes/:
    get:
      operationId: quotes_list
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - quotes
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedQuoteList'
          description: ''
    post:
      operationId: quotes_create
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      tags:
      - quotes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Quote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Quote'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          description: ''
  /api/quotes/{id}/:
    get:
      operationId: quotes_retrieve
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quote.
        required: true
      tags:
      - quotes
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          description: ''
    put:
      operationId: quotes_update
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quote.
        required: true
      tags:
      - quotes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Quote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Quote'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          description: ''
    patch:
      operationId: quotes_partial_update
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quote.
        required: true
      tags:
      - quotes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedQuote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedQuote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedQuote'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          description: ''
    delete:
      operationId: quotes_destroy
      description: |-
        API endpoint that allows quotes to be viewed.

        Endpoints:
        - GET /api/quotes/       -> Retrieve all quotes
        - POST /api/quotes/      -> Create a new quote
        - GET /api/quotes/{id}/  -> Retrieve a specific quote
        - PUT /api/quotes/{id}/  -> Update a quote
        - DELETE /api/quotes/{id}/ -> Delete a quote
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this quote.
        required: true
      tags:
      - quotes
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/quotes/random/:
    get:
      operationId: quotes_random_retrieve
      description: |-
        Retrieve a random quote from the database.
        - Returns a 200 status code with a random quote if available.
        - Returns a 404 status code with an appropriate message if no quotes exist.
      tags:
      - quotes
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          description: ''
  /api/users/register/:
    post:
      operationId: users_register_create
      description: Creates a new user and returns an authentication token.
      summary: User Registration
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                example:
                  id: 1
                  username: newuser
                  email: newuser@example.com
                  token: abc123xyz
          description: ''
components:
  schemas:
    PaginatedQuoteList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Quote'
    PatchedQuote:
      type: object
      description: |-
        Serializer for the Quote model.
        Transforms Quote instances into JSON and validates input data for API requests.
      properties:
        id:
          type: integer
          readOnly: true
        author:
          type: string
          description: The author of the quote.
          maxLength: 255
        content:
          type: string
          description: The content of the quote.
        timestamp:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp when the quote was created.
    Quote:
      type: object
      description: |-
        Serializer for the Quote model.
        Transforms Quote instances into JSON and validates input data for API requests.
      properties:
        id:
          type: integer
          readOnly: true
        author:
          type: string
          description: The author of the quote.
          maxLength: 255
        content:
          type: string
          description: The content of the quote.
        timestamp:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp when the quote was created.
      required:
      - author
      - content
      - id
      - timestamp
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
      required:
      - id
      - password
      - username
  securitySchemes:
    oauth2:
      type: oauth2
      flows: {}
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
